ExamSys/urls.py
from django.contrib import admin
# from exam.admin import admin_site
from django.urls import path, include, re_path
from django.views.static import serve
from ExamSys.settings import MEDIA_ROOT
try:
    from ExamSys.settings import STATIC_ROOT
except:
    from ExamSys.settings import STATICFILES_DIRS
    STATIC_ROOT = STATICFILES_DIRS[0]
# from django.conf import settings
# from django.conf.urls.static import static
from exam.views import *


urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('exam_page/', ExamPage.as_view(), name='exam_page'),
    path('final_page/', ExamPage.as_view(), name='final_page'),

    path('admin/', admin.site.urls),
    # path('admin/', admin_site.urls),

    # 用户管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    # path('password-reset/', include('password_reset.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')), #添加ckeditor的url到项目中

    # Static 文件
    re_path(r'^media/(?P<path>.*)/$', serve, {"document_root": MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)/$', serve, {"document_root": STATIC_ROOT}),
]

apps/userprofile/urls.py
# -*- coding: utf-8 -*-
"""
Created by @南卡统爷 on 3/27/20 11:26 PM.
"""
__author__ = '@SCTongYe'

from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录登出
    path('login/', views.User_login.as_view(), name='login'),
    path('logout/', views.User_logout.as_view(), name='logout'),

    # # 用户注册
    # path('register/', views.User_register.as_view(), name='register'),

    # 用户删除
    path('delete/<int:id>/', views.User_delete.as_view(), name='delete'),

    # 用户信息
    path('edit/<int:id>/', views.Profile_edit.as_view(), name='edit'),


]

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="zh-cn">
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
  <link rel="stylesheet" href="{% static 'prism/prism.css' %}">
  <link rel="stylesheet"
        href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
        crossorigin="anonymous"
  >
  <link href="https://fonts.googleapis.com/css2?family=Exo&family=Special+Elite&display=swap" rel="stylesheet">
  <style>
    html, body {
      height: 100%;
      margin: 0;
      font-family: 'Exo', sans-serif;
    }

    #wrapper {
      min-height: 100%;
      margin-bottom: -60px;
    }

    #footer,
    #push {
      height: 60px;
    }

    input {
      margin-right: 5px;
    }

    .navbar-custom {
      background-color: #39ff14;
      color: #1d2124;
    }

    .navbar-custom a:link {
      color: #1d2124;
    }

    .navbar-custom a:visited {
      color: #1d2124;
    }

    .question_type{
      font-size: 12px;
      font-style: oblique;
    }


  </style>
</head>

<body>
{% include 'header.html' %}
<div id="wrapper">
  {% block content %}{% endblock content %}
  <div id="push"></div>
</div>
{% include 'footer.html' %}
<script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'popper/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'layer/layer.js' %}"></script>
<script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
{% block script %}{% endblock script %}
</body>

</html>

templates/footer.html
{% load static %}
<div>
  <br><br><br>
</div>
<footer class="py-3 bg-dark" id="footer">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; 2007 -
      <script language="javascript" type="text/javascript">
        var today = new Date()
        var year = today.getFullYear()
        document.write(year)
      </script>
       <a href="http://www.sommersydnie.com">Sommer & Sydnie</a>. All Rights Reserved
    </p>
  </div>
</footer>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-custom">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}"><i class="fas fa-edit" style="color:#FF6DCE"></i> Online Test System for Sommer & Sydnie</a>
    <div>
      <ul class="navbar-nav">

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="#">Ready?</a>
        </li>
        {% endif %}

        {% if user.is_authenticated %}

          {% if user.profile.avatar.url %}
          <li class="nav-item">
          <a class="nav-link" href="#"><img src="{{ user.profile.avatar.url }}" alt="" class="rounded-circle" style="width:30px; height: 30px;"></a>
          </li>
          {% endif %}
          
          
          <li class="nav-item dropdown">

            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">

              {{ user.username }}

            </a>


            <div class="dropdown-menu" aria-labelledby="navbarDropdown">


              <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>Info</a>

              <a class="dropdown-item" href='{% url "userprofile:logout" %}'>Logout</a>

            </div>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url "userprofile:login" %}">Please Login</a>
          </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>